### PR TITLE
Docs to reStructuredText

### PR DESCRIPTION
**Pull request by aawdls**
Converting manual to reStructuredText at the 2020 Codeathon

cc @MarkRivers @GDYendell

### CODE REVIEW

**Review by MarkRivers — CHANGES_REQUESTED** [review]
This looks good, thanks.

Some comments:
- Please don't delete the documentation/pvaDriverDoc.html yet.  We might want it for reference.
- We have been using internal links for the files you have used absolute links at the end
- You can add suggested widths in percent to the flat-table to improve appearance
- I have been adding a "literal-include" of the st.cmd file in the documentation itself.

**Comment by aawdls** [comment]
Thanks for the feedback. For the relative links, I'll copy the format from ADAndor, e.g.
```
../areaDetectorDoxygenHTML/asyn_n_d_array_driver_8h.html
```

**Comment by aawdls** [comment]
Just a thought also, it looks like the Supported Detectors page might need some updates: ADAravis is not listed, and some of the documentation links are broken

**Comment by aawdls** [comment]
The page title is inconsistent with the others so far. I will change "areaDetector pvAccess driver" to a subittle and make the page title "pvaDriver"

**Comment by MarkRivers** [comment]
>Just a thought also, it looks like the Supported Detectors page might need some updates: ADAravis is not listed, and some of the documentation links are broken

You mean this page?
https://areadetector.github.io/master/detectors.html

We need to decide if that page is useful and should be maintained.

**Pull request merged**
